export const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAILURE = "MOVIE_GET_FAILURE";

export const MOVIE_DATA_GET_REQUEST = "MOVIE_DATA_GET_REQUEST";
export const MOVIE_DATA_GET_SUCCESS = "MOVIE_DATA_GET_SUCCESS";
export const MOVIE_DATA_GET_FAILURE = "MOVIE_DATA_GET_FAILURE";

export const MOVIE_DATA_POST_REQUEST = "MOVIE_DATA_POST_REQUEST";
export const MOVIE_DATA_POST_SUCCESS = "MOVIE_DATA_POST_SUCCESS";
export const MOVIE_DATA_POST_FAILURE = "MOVIE_DATA_POST_FAILURE";

export const MOVIE_DATA_EDIT_REQUEST = "MOVIE_DATA_EDIT_REQUEST";
export const MOVIE_DATA_EDIT_SUCCESS = "MOVIE_DATA_EDIT_SUCCESS";
export const MOVIE_DATA_EDIT_FAILURE = "MOVIE_DATA_EDIT_FAILURE";

export const MOVIE_DATA_DELETE_REQUEST = "MOVIE_DATA_DELETE_REQUEST";
export const MOVIE_DATA_DELETE_SUCCESS = "MOVIE_DATA_DELETE_SUCCESS";
export const MOVIE_DATA_DELETE_FAILURE = "MOVIE_DATA_DELETE_FAILURE";
